{
 "title": "Envoy Proxy Monitoring gRPC",
 "description": "A comprehensive dashboard for real-time monitoring of Envoy Proxy metrics using Prometheus.\r\nIncludes upstream/downstream request rates, memory usage, gRPC status codes, connection resets, latency percentiles (p95/p99), cluster health, and traffic in/out — with built-in IP/cluster filtering and clear color-coded visualization.\r\nPerfect for high-performance gRPC, HTTP/1/2/3, and service mesh environments.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total,envoy_cluster_name)"
    }
   },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy)  - sum(envoy_cluster_membership_total))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
    }
   ]
  },
  {
   "title": "Downstream Traffic (Bytes In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_rx_bytes_total{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "Incoming Bytes"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_total{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "Outgoing Bytes"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{instance=~\"$hosts\"}[1m])) by (response_code_class)",
     "legendFormat": "Downstream request"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{instance=~\"$hosts\"}[1m])) by (response_code_class)",
     "legendFormat": "UPstream request"
    }
   ]
  },
  {
   "title": "All HTTP Response & Active Downstream Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "0xx Success Downstream"
    },
    {
     "expr": "sum by (hosts) (rate(envoy_cluster_upstream_cx_http1_total{instance=~\"$hosts\"}[$__rate_interval]))",
     "legendFormat": "1xx Canceled"
    },
    {
     "expr": "sum by (hosts) (rate(envoy_cluster_upstream_cx_http2_total{instance=~\"$hosts\"}[$__rate_interval]))",
     "legendFormat": "2xx Unknown"
    },
    {
     "expr": "sum by (hosts) (rate(envoy_cluster_upstream_cx_http3_total{instance=~\"$hosts\"}[$__rate_interval]))",
     "legendFormat": "3xx InvalidArgument"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "0xx Success Upstream"
    }
   ]
  },
  {
   "title": "Upstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "gRPC RPS"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_active{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "gRPC RPS"
    }
   ]
  },
  {
   "title": "gRPC Status Codes",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 24 },
   "targets": [
    {
     "expr": "sum by (grpc_response_code) (rate(envoy_cluster_external_upstream_rq_xx{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "{{grpc_response_code}}"
    }
   ]
  },
  {
   "title": "Connection Resets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_local_active_rq{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "Resets/sec"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "Resets/sec"
    }
   ]
  },
  {
   "title": "Downstream Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{instance=~\"$hosts\"}[1m]))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "95th & 99th Percentile Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{instance=~\"$hosts\"}[1m])) by (le, cluster))",
     "legendFormat": "95 Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{instance=~\"$hosts\"}[1m])) by (le, cluster))",
     "legendFormat": "99 Percentile"
    }
   ]
  },
  {
   "title": "Error Rate (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{instance=~\"$hosts\",envoy_response_code_class=~\"4|5\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}xx"
    }
   ]
  }
 ]
}