global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [ 'nginx_exporter_thrift:9113' ]
    metrics_path: '/metrics'

  - job_name: 'telegraf'
    static_configs:
      - targets: [ 'telegraf_thrift:9273' ]
    metrics_path: '/metrics'

  - job_name: 'thrift-backend'
    static_configs:
      - targets: ['thrift_backend1:9090', 'thrift_backend2:9090']
    metrics_path: '/actuator/prometheus'
